* Chi square test or Fisher Score

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
titanic = sns.load_dataset('titanic')

In [5]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [6]:
test_data = data[['sex','embarked','alone','pclass','survived']]

In [7]:
test_data.head()

      sex embarked  alone  pclass  survived
0    male        S  False       3         0
1  female        C  False       1         1
2  female        S   True       3         1
3  female        S  False       1         1
4    male        S   True       3         0

* For Perform chi-square test, first we need to encode the data and train test split.

In [9]:
test_data['sex'] = np.where(test_data['sex'] == 'male',1,0)

C:\Users\aravi\anaconda3\envs\tensflow\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [10]:
label = {k:i for i,k in enumerate(test_data['embarked'].unique(),0)}

In [11]:
label

{'S': 0, 'C': 1, 'Q': 2, nan: 3}

In [12]:
test_data.embarked = test_data.embarked.map(label)

C:\Users\aravi\anaconda3\envs\tensflow\lib\site-packages\pandas\core\generic.py:5516: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [13]:
test_data.alone = np.where(test_data.alone == True, 1,0)

In [14]:
test_data.head()

   sex  embarked  alone  pclass  survived
0    1         0      0       3         0
1    0         1      0       1         1
2    0         0      1       3         1
3    0         0      0       1         1
4    1         0      1       3         0

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X = test_data.drop('survived',axis = 1)
y = test_data.survived

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [18]:
# lets perform Chi2 test

In [19]:
from sklearn.feature_selection import chi2

In [20]:
chi = chi2(X_train, y_train)

In [21]:
chi

(array([57.2929115 , 10.84277841,  6.89893102, 16.75879411]),
 array([3.75506162e-14, 9.91818014e-04, 8.62473049e-03, 4.24450830e-05]))

* The First value is F-score (the more the F score we can take the value)
* The Second valus is PValue (the lesser the P value we can take the value)

In [31]:
p_values = pd.Series(chi[1])
p_values.index = ['sex', 'embarked', 'alone', 'pclass']

In [33]:
p_values

sex         3.755062e-14
embarked    9.918180e-04
alone       8.624730e-03
pclass      4.244508e-05
dtype: float64

In [34]:
p_values.sort_index(ascending = False)

sex         3.755062e-14
pclass      4.244508e-05
embarked    9.918180e-04
alone       8.624730e-03
dtype: float64

In [35]:
# The lesser the P value we can take

In [36]:
F_score = pd.Series(chi[0])
F_score.index = ['sex', 'embarked', 'alone', 'pclass']

In [39]:
F_score.sort_index(ascending = False)

sex         57.292912
pclass      16.758794
embarked    10.842778
alone        6.898931
dtype: float64

In [40]:
# The higher the F Score we can take.

* Observations: