In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.DataFrame({'A':[1,2,3,4,5],'B':[2,4,2,4,3],'C':[0,0,0,0,0],'D':[1,1,1,1,1]})

In [3]:
data.head()

   A  B  C  D
0  1  2  0  1
1  2  4  0  1
2  3  2  0  1
3  4  4  0  1
4  5  3  0  1

In [4]:
#lets create a dataframe and we can do the feature selection here! 
# this is unsupervised model.

In [5]:
# lot's of techniques here we use droping the constant features using the constant threshold!

* Here's the link for documentation 
*  https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.VarianceThreshold.html

* It looks for only X value and it don't need the output value.
* It will remove the 0 variance value.

In [6]:
from sklearn.feature_selection import VarianceThreshold

In [7]:
vt = VarianceThreshold(threshold = 0) # It will remove the 0 variance value. 
vt.fit(data) # for example this is my X feature

VarianceThreshold(threshold=0)

In [8]:
vt.get_support() # false are 0 variance value, let's remove this

array([ True,  True, False, False])

In [9]:
remove_values = [i for i in data.columns if i not in data.columns[vt.get_support()] ]

In [10]:
remove_values

['C', 'D']

In [11]:
data.drop(remove_values,axis = 1, inplace = True)

In [12]:
data.head() # this values only we needed to do the calculations.

   A  B
0  1  2
1  2  4
2  3  2
3  4  4
4  5  3

In [13]:
# let's do in the real world seneraio!

In [14]:
data = pd.read_csv('Travel.csv') # Don't worry Csv is provided in this folder!

In [15]:
data.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [16]:
data.shape

(4888, 20)

In [17]:
datas = [i  for i in data.columns if data[i].dtype == 'O']

In [18]:
datas # this are all the categorical features so i will remove from the dataset.
     # I not going to do any preprocessing this is for just only for feature selection.

['TypeofContact',
 'Occupation',
 'Gender',
 'ProductPitched',
 'MaritalStatus',
 'Designation']

In [19]:
data.drop(datas, axis = 1, inplace = True)

In [20]:
data.head()

,CustomerID,ProdTaken,Age,CityTier,DurationOfPitch,NumberOfPersonVisiting,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,MonthlyIncome
0,200000,1,41.0,3,6.0,3,3.0,3.0,1.0,1,2,1,0.0,20993.0
1,200001,0,49.0,1,14.0,3,4.0,4.0,2.0,0,3,1,2.0,20130.0
2,200002,1,37.0,1,8.0,3,4.0,3.0,7.0,1,3,0,0.0,17090.0
3,200003,0,33.0,1,9.0,2,3.0,3.0,2.0,1,5,1,1.0,17909.0
4,200004,0,NaN,1,8.0,2,3.0,4.0,1.0,0,5,1,0.0,18468.0

In [21]:

X = data.drop('MonthlyIncome',axis = 1)
y = data['MonthlyIncome']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [22]:
# Now we have a numerical dataset so we do the feature selection.

In [23]:
from sklearn.feature_selection import VarianceThreshold

In [30]:
vt = VarianceThreshold(threshold = 1)
vt.fit(X_train)
# For Zero there is no False values that's why I choosed the threshold value is 2

VarianceThreshold(threshold=1)

In [31]:
vt.get_support()

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False, False])

In [34]:
remove_values = [i for i in X_train.columns if i not in X_train.columns[vt.get_support()]]

In [35]:
remove_values # This values are not needed for our data so I go to delete drop this.

['ProdTaken',
 'CityTier',
 'NumberOfPersonVisiting',
 'PreferredPropertyStar',
 'Passport',
 'OwnCar',
 'NumberOfChildrenVisiting']

In [40]:
X_train.drop(remove_values,axis = 1)

,CustomerID,Age,DurationOfPitch,NumberOfFollowups,NumberOfTrips,PitchSatisfactionScore
2962,202962,39.0,14.0,5.0,2.0,2
1788,201788,27.0,11.0,3.0,2.0,3
3499,203499,35.0,22.0,4.0,NaN,4
3173,203173,36.0,32.0,4.0,3.0,3
3126,203126,33.0,7.0,5.0,8.0,3
...,...,...,...,...,...,...
4426,204426,28.0,10.0,5.0,2.0,1
466,200466,41.0,8.0,3.0,1.0,5
3092,203092,38.0,28.0,4.0,7.0,2
3772,203772,28.0,30.0,5.0,3.0,1
860,200860,22.0,9.0,4.0,1.0,3

In [ ]:
# then after that we can for for model building!