* This is for nominal dtype.

In [2]:
import pandas as pd
import seaborn as sns
import numpy as np 
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
data = pd.read_csv('train_mercedz_benz.csv',usecols = ['X1','X2'])

In [5]:
data.head()

  X1  X2
0  v  at
1  t  av
2  w   n
3  t   n
4  v   n

In [9]:
pd.get_dummies(data,drop_first = True).shape
# Here we have 69 features but the orginal data contains only 2 for that we use the count encoding.

(4209, 69)

In [10]:
len(data.X1.unique()) # 27 features are there

27

In [12]:
x1 = data.X1.value_counts().to_dict()

In [13]:
data.X1 = data.X1.map(x1)

In [14]:
data.head()

    X1  X2
0  408  at
1   31  av
2   52   n
3   31   n
4  408   n

In [15]:
x1

{'aa': 833,
 's': 598,
 'b': 592,
 'l': 590,
 'v': 408,
 'r': 251,
 'i': 203,
 'a': 143,
 'c': 121,
 'o': 82,
 'w': 52,
 'z': 46,
 'u': 37,
 'e': 33,
 'm': 32,
 't': 31,
 'h': 29,
 'y': 23,
 'f': 23,
 'j': 22,
 'n': 19,
 'k': 17,
 'p': 9,
 'g': 6,
 'd': 3,
 'q': 3,
 'ab': 3}