In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
%matplotlib inline

In [3]:
data = pd.read_csv('train_titanic.csv', usecols = ['Sex'])

In [4]:
data.head()

      Sex
0    male
1  female
2  female
3  female
4    male

# NOMINAL ENCODING

### 1. One hot encoding.

In [6]:
pd.get_dummies(data,drop_first = True)

     Sex_male
0           1
1           0
2           0
3           0
4           1
..        ...
886         1
887         0
888         0
889         1
890         1

[891 rows x 1 columns]

In [7]:
data = pd.read_csv('train_titanic.csv', usecols = ['Embarked'])

In [9]:
data.Embarked.unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [10]:
data.dropna(inplace = True)

In [12]:
pd.get_dummies(data, drop_first = True)

     Embarked_Q  Embarked_S
0             0           1
1             0           0
2             0           1
3             0           1
4             0           1
..          ...         ...
886           0           1
887           0           1
888           0           1
889           0           0
890           1           0

[889 rows x 2 columns]

### 2. One hot encoding with many Categorical variabels..

In [35]:
data = pd.read_csv('train_mercedz_benz.csv',usecols = ['X0','X1','X2','X3','X4','X5'])

In [36]:
data.head()

   X0 X1  X2 X3 X4 X5
0   k  v  at  a  d  u
1   k  t  av  e  d  y
2  az  w   n  c  d  x
3  az  t   n  f  d  x
4  az  v   n  f  d  h

In [37]:
data.shape

(4209, 6)

In [38]:
data.X0.value_counts().sort_values(ascending = False).head(10)

z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
Name: X0, dtype: int64

In [39]:
data.X1.value_counts().sort_values(ascending = False).head(10).index.to_list()

['aa', 's', 'b', 'l', 'v', 'r', 'i', 'a', 'c', 'o']

In [40]:
ls = ['aa', 's', 'b', 'l', 'v', 'r', 'i', 'a', 'c', 'o']

In [50]:
for i in ls:
    data[i] = np.where(data['X1'] == i, 1, 0)

In [51]:
data.X1.value_counts()

aa    833
s     598
b     592
l     590
v     408
r     251
i     203
a     143
c     121
o      82
w      52
z      46
u      37
e      33
m      32
t      31
h      29
y      23
f      23
j      22
n      19
k      17
p       9
g       6
d       3
q       3
ab      3
Name: X1, dtype: int64

In [52]:
data[['X1'] + ls].head()

  X1  aa  s  b  l  v  r  i  a  c  o
0  v   0  0  0  0  1  0  0  0  0  0
1  t   0  0  0  0  0  0  0  0  0  0
2  w   0  0  0  0  0  0  0  0  0  0
3  t   0  0  0  0  0  0  0  0  0  0
4  v   0  0  0  0  1  0  0  0  0  0

### 3. Count of Frequency encoding

In [93]:
train_set = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data' , 
                        header = None,index_col=None) 
train_set.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [ ]:
col = [1,3,5,6,7,8,9,13]

In [94]:
train = train_set[col]

In [95]:
train.columns = ['Employment', 'Degree', 'Status', 'Designation', 'family_job', 'Race', 'Sex','Country']

In [96]:
a = train['Country'].value_counts().to_dict()

In [97]:
train['Country'] = train['Country'].map(a)

C:\Users\aravi\anaconda3\envs\tensflow\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [98]:
train.head()

,Employment,Degree,Status,Designation,family_job,Race,Sex,Country
0,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,29170
1,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,29170
2,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,29170
3,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,29170
4,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,95

### 4. Mean Encoding

In [115]:
data = pd.read_csv('train_titanic.csv', usecols = ['Cabin','Survived'])

In [122]:
data.head()

   Survived     Cabin
0         0  0.299854
1         1  1.000000
2         1  0.299854
3         1  0.500000
4         0  0.299854

In [116]:
data.Cabin.fillna('theriyathu', inplace = True)

In [119]:
di = data.groupby(['Cabin'])['Survived'].mean().to_dict() # just checking the nr of percentage pepole survived

In [120]:
data.Cabin = data.Cabin.map(di)

In [121]:
data.head()

   Survived     Cabin
0         0  0.299854
1         1  1.000000
2         1  0.299854
3         1  0.500000
4         0  0.299854

# ORDINAL ENCODING

### 1. Ordianal number Encoding

In [53]:
import datetime

In [56]:
today_date = datetime.datetime.today()

In [57]:
data = [today_date - datetime.timedelta(X) for X in range(0,15)]

In [58]:
data

[datetime.datetime(2021, 8, 31, 14, 50, 47, 796358),
 datetime.datetime(2021, 8, 30, 14, 50, 47, 796358),
 datetime.datetime(2021, 8, 29, 14, 50, 47, 796358),
 datetime.datetime(2021, 8, 28, 14, 50, 47, 796358),
 datetime.datetime(2021, 8, 27, 14, 50, 47, 796358),
 datetime.datetime(2021, 8, 26, 14, 50, 47, 796358),
 datetime.datetime(2021, 8, 25, 14, 50, 47, 796358),
 datetime.datetime(2021, 8, 24, 14, 50, 47, 796358),
 datetime.datetime(2021, 8, 23, 14, 50, 47, 796358),
 datetime.datetime(2021, 8, 22, 14, 50, 47, 796358),
 datetime.datetime(2021, 8, 21, 14, 50, 47, 796358),
 datetime.datetime(2021, 8, 20, 14, 50, 47, 796358),
 datetime.datetime(2021, 8, 19, 14, 50, 47, 796358),
 datetime.datetime(2021, 8, 18, 14, 50, 47, 796358),
 datetime.datetime(2021, 8, 17, 14, 50, 47, 796358)]

In [59]:
data = pd.DataFrame(data)

In [60]:
data.columns = ['Day']

In [61]:
data.head()

                         Day
0 2021-08-31 14:50:47.796358
1 2021-08-30 14:50:47.796358
2 2021-08-29 14:50:47.796358
3 2021-08-28 14:50:47.796358
4 2021-08-27 14:50:47.796358

In [71]:
li = ['monday','tuesday','wednesday','thursday','friday','saturday','sunday'
     'monday','tuesday','wednesday','thursday','friday','saturday','sunday','monday','tuesday']

In [72]:
data['weekday'] = li

In [73]:
data.head()

                         Day    weekday
0 2021-08-31 14:50:47.796358     monday
1 2021-08-30 14:50:47.796358    tuesday
2 2021-08-29 14:50:47.796358  wednesday
3 2021-08-28 14:50:47.796358   thursday
4 2021-08-27 14:50:47.796358     friday

In [74]:
dic = {'monday':1,'tuesday':2,'wednesday':3,'thursday':4,'friday':5,'saturday':6,'sunday':7}

In [75]:
data['weekday'] = data['weekday'].map(dic)

In [76]:
data.head()

                         Day  weekday
0 2021-08-31 14:50:47.796358      1.0
1 2021-08-30 14:50:47.796358      2.0
2 2021-08-29 14:50:47.796358      3.0
3 2021-08-28 14:50:47.796358      4.0
4 2021-08-27 14:50:47.796358      5.0

### 2. Target Guided Ordianl Encoding

In [99]:
data = pd.read_csv('train_titanic.csv', usecols = ['Cabin','Survived'])

In [103]:
data.head(15)

    Survived       Cabin
0          0  theriyathu
1          1         C85
2          1  theriyathu
3          1        C123
4          0  theriyathu
5          0  theriyathu
6          0         E46
7          0  theriyathu
8          1  theriyathu
9          1  theriyathu
10         1          G6
11         1        C103
12         0  theriyathu
13         0  theriyathu
14         0  theriyathu

In [102]:
data.Cabin.fillna('theriyathu', inplace = True)

In [105]:
data['Cabin'] = data.Cabin.astype(str).str[0]

In [106]:
data.Cabin.unique()

array(['t', 'C', 'E', 'G', 'D', 'A', 'B', 'F', 'T'], dtype=object)

In [107]:
data.groupby(['Cabin'])['Survived'].mean() # just checking the nr of percentage pepole survived

Cabin
A    0.466667
B    0.744681
C    0.593220
D    0.757576
E    0.750000
F    0.615385
G    0.500000
T    0.000000
t    0.299854
Name: Survived, dtype: float64

In [109]:
data.groupby(['Cabin'])['Survived'].mean().sort_values().index

Index(['T', 't', 'A', 'G', 'C', 'F', 'B', 'E', 'D'], dtype='object', name='Cabin')

In [110]:
lab = ['T', 't', 'A', 'G', 'C', 'F', 'B', 'E', 'D']

In [112]:
lab2 = {k:i for i,k in enumerate(lab, 0) }

In [113]:
data.Cabin = data.Cabin.map(lab2)

In [114]:
data.head()

   Survived  Cabin
0         0      1
1         1      4
2         1      1
3         1      4
4         0      1