In [1]:
import pandas as pd
import numpy as np

In [2]:
import seaborn as sns

In [3]:
data = pd.read_csv('train_mercedz_benz.csv')

In [4]:
data.isnull().sum()

ID      0
y       0
X0      0
X1      0
X2      0
       ..
X380    0
X382    0
X383    0
X384    0
X385    0
Length: 378, dtype: int64

In [5]:
# Our Main motto is we can do easily one hot encoding for 2 to 3 features, but consider if we have more 
# -- more than 100, so we do simple encoding let's see below

In [6]:
data.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [11]:
data.info

<bound method DataFrame.info of         ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ...  X375  X376  X377  X378  \
0        0  130.81   k  v  at  a  d   u  j  o  ...     0     0     1     0
1        6   88.53   k  t  av  e  d   y  l  o  ...     1     0     0     0
2        7   76.26  az  w   n  c  d   x  j  x  ...     0     0     0     0
3        9   80.62  az  t   n  f  d   x  l  e  ...     0     0     0     0
4       13   78.02  az  v   n  f  d   h  d  n  ...     0     0     0     0
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...   ...   ...   ...   ...
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...     1     0     0     0
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...     0     1     0     0
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...     0     0     1     0
4207  8415   87.48  al  r   e  f  d  aa  l  u  ...     0     0     0     0
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...     1     0     0     0

      X379  X380  X382  X383  X384  X385
0        0     0     0     0     0     0
1        0     0     0     0     0     0
2        0     0     1     0     0     0
3        0     0     0     0     0     0
4        0     0     0     0     0     0
...    ...   ...   ...   ...   ...   ...
4204     0     0     0     0     0     0
4205     0     0     0     0     0     0
4206     0     0     0     0     0     0
4207     0     0     0     0     0     0
4208     0     0     0     0     0     0

[4209 rows x 378 columns]>

In [9]:
data.describe()

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.0,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4205.960798,100.669318,0.013305,0.0,0.075077,0.057971,0.428130,0.000475,0.002613,0.007603,...,0.318841,0.057258,0.314802,0.020670,0.009503,0.008078,0.007603,0.001663,0.000475,0.001426
std,2437.608688,12.679381,0.114590,0.0,0.263547,0.233716,0.494867,0.021796,0.051061,0.086872,...,0.466082,0.232363,0.464492,0.142294,0.097033,0.089524,0.086872,0.040752,0.021796,0.037734
min,0.000000,72.110000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2095.000000,90.820000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4220.000000,99.150000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6314.000000,109.010000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8417.000000,265.320000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [14]:
for i in data.columns:
    print(i, type(i))

ID <class 'str'>
y <class 'str'>
X0 <class 'str'>
X1 <class 'str'>
X2 <class 'str'>
X3 <class 'str'>
X4 <class 'str'>
X5 <class 'str'>
X6 <class 'str'>
X8 <class 'str'>
X10 <class 'str'>
X11 <class 'str'>
X12 <class 'str'>
X13 <class 'str'>
X14 <class 'str'>
X15 <class 'str'>
X16 <class 'str'>
X17 <class 'str'>
X18 <class 'str'>
X19 <class 'str'>
X20 <class 'str'>
X21 <class 'str'>
X22 <class 'str'>
X23 <class 'str'>
X24 <class 'str'>
X26 <class 'str'>
X27 <class 'str'>
X28 <class 'str'>
X29 <class 'str'>
X30 <class 'str'>
X31 <class 'str'>
X32 <class 'str'>
X33 <class 'str'>
X34 <class 'str'>
X35 <class 'str'>
X36 <class 'str'>
X37 <class 'str'>
X38 <class 'str'>
X39 <class 'str'>
X40 <class 'str'>
X41 <class 'str'>
X42 <class 'str'>
X43 <class 'str'>
X44 <class 'str'>
X45 <class 'str'>
X46 <class 'str'>
X47 <class 'str'>
X48 <class 'str'>
X49 <class 'str'>
X50 <class 'str'>
X51 <class 'str'>
X52 <class 'str'>
X53 <class 'str'>
X54 <class 'str'>
X55 <class 'str'>
X56 <class 'str'>
X57 <class 'str'>
X58 <class 'str'>
X59 <class 'str'>
X60 <class 'str'>
X61 <class 'str'>
X62 <class 'str'>
X63 <class 'str'>
X64 <class 'str'>
X65 <class 'str'>
X66 <class 'str'>
X67 <class 'str'>
X68 <class 'str'>
X69 <class 'str'>
X70 <class 'str'>
X71 <class 'str'>
X73 <class 'str'>
X74 <class 'str'>
X75 <class 'str'>
X76 <class 'str'>
X77 <class 'str'>
X78 <class 'str'>
X79 <class 'str'>
X80 <class 'str'>
X81 <class 'str'>
X82 <class 'str'>
X83 <class 'str'>
X84 <class 'str'>
X85 <class 'str'>
X86 <class 'str'>
X87 <class 'str'>
X88 <class 'str'>
X89 <class 'str'>
X90 <class 'str'>
X91 <class 'str'>
X92 <class 'str'>
X93 <class 'str'>
X94 <class 'str'>
X95 <class 'str'>
X96 <class 'str'>
X97 <class 'str'>
X98 <class 'str'>
X99 <class 'str'>
X100 <class 'str'>
X101 <class 'str'>
X102 <class 'str'>
X103 <class 'str'>
X104 <class 'str'>
X105 <class 'str'>
X106 <class 'str'>
X107 <class 'str'>
X108 <class 'str'>
X109 <class 'str'>
X110 <class 'str'>
X111 <class 'str'>
X112 <class 'str'>
X113 <class 'str'>
X114 <class 'str'>
X115 <class 'str'>
X116 <class 'str'>
X117 <class 'str'>
X118 <class 'str'>
X119 <class 'str'>
X120 <class 'str'>
X122 <class 'str'>
X123 <class 'str'>
X124 <class 'str'>
X125 <class 'str'>
X126 <class 'str'>
X127 <class 'str'>
X128 <class 'str'>
X129 <class 'str'>
X130 <class 'str'>
X131 <class 'str'>
X132 <class 'str'>
X133 <class 'str'>
X134 <class 'str'>
X135 <class 'str'>
X136 <class 'str'>
X137 <class 'str'>
X138 <class 'str'>
X139 <class 'str'>
X140 <class 'str'>
X141 <class 'str'>
X142 <class 'str'>
X143 <class 'str'>
X144 <class 'str'>
X145 <class 'str'>
X146 <class 'str'>
X147 <class 'str'>
X148 <class 'str'>
X150 <class 'str'>
X151 <class 'str'>
X152 <class 'str'>
X153 <class 'str'>
X154 <class 'str'>
X155 <class 'str'>
X156 <class 'str'>
X157 <class 'str'>
X158 <class 'str'>
X159 <class 'str'>
X160 <class 'str'>
X161 <class 'str'>
X162 <class 'str'>
X163 <class 'str'>
X164 <class 'str'>
X165 <class 'str'>
X166 <class 'str'>
X167 <class 'str'>
X168 <class 'str'>
X169 <class 'str'>
X170 <class 'str'>
X171 <class 'str'>
X172 <class 'str'>
X173 <class 'str'>
X174 <class 'str'>
X175 <class 'str'>
X176 <class 'str'>
X177 <class 'str'>
X178 <class 'str'>
X179 <class 'str'>
X180 <class 'str'>
X181 <class 'str'>
X182 <class 'str'>
X183 <class 'str'>
X184 <class 'str'>
X185 <class 'str'>
X186 <class 'str'>
X187 <class 'str'>
X189 <class 'str'>
X190 <class 'str'>
X191 <class 'str'>
X192 <class 'str'>
X194 <class 'str'>
X195 <class 'str'>
X196 <class 'str'>
X197 <class 'str'>
X198 <class 'str'>
X199 <class 'str'>
X200 <class 'str'>
X201 <class 'str'>
X202 <class 'str'>
X203 <class 'str'>
X204 <class 'str'>
X205 <class 'str'>
X206 <class 'str'>
X207 <class 'str'>
X208 <class 'str'>
X209 <class 'str'>
X210 <class 'str'>
X211 <class 'str'>
X212 <class 'str'>
X213 <class 'str'>
X214 <class 'str'>
X215 <class 'str'>
X216 <class 'str'>
X217 <class 'str'>
X218 <class 'str'>
X219 <class 'str'>
X220 <class 'str'>
X221 <class 'str'>
X222 <class 'str'>
X223 <class 'str'>
X224 <class 'str'>
X225 <class 'str'>
X226 <class 'str'>
X227 <class 'str'>
X228 <class 'str'>
X229 <class 'str'>
X230 <class 'str'>
X231 <class 'str'>
X232 <class 'str'>
X233 <class 'str'>
X234 <class 'str'>
X235 <class 'str'>
X236 <class 'str'>
X237 <class 'str'>
X238 <class 'str'>
X239 <class 'str'>
X240 <class 'str'>
X241 <class 'str'>
X242 <class 'str'>
X243 <class 'str'>
X244 <class 'str'>
X245 <class 'str'>
X246 <class 'str'>
X247 <class 'str'>
X248 <class 'str'>
X249 <class 'str'>
X250 <class 'str'>
X251 <class 'str'>
X252 <class 'str'>
X253 <class 'str'>
X254 <class 'str'>
X255 <class 'str'>
X256 <class 'str'>
X257 <class 'str'>
X258 <class 'str'>
X259 <class 'str'>
X260 <class 'str'>
X261 <class 'str'>
X262 <class 'str'>
X263 <class 'str'>
X264 <class 'str'>
X265 <class 'str'>
X266 <class 'str'>
X267 <class 'str'>
X268 <class 'str'>
X269 <class 'str'>
X270 <class 'str'>
X271 <class 'str'>
X272 <class 'str'>
X273 <class 'str'>
X274 <class 'str'>
X275 <class 'str'>
X276 <class 'str'>
X277 <class 'str'>
X278 <class 'str'>
X279 <class 'str'>
X280 <class 'str'>
X281 <class 'str'>
X282 <class 'str'>
X283 <class 'str'>
X284 <class 'str'>
X285 <class 'str'>
X286 <class 'str'>
X287 <class 'str'>
X288 <class 'str'>
X289 <class 'str'>
X290 <class 'str'>
X291 <class 'str'>
X292 <class 'str'>
X293 <class 'str'>
X294 <class 'str'>
X295 <class 'str'>
X296 <class 'str'>
X297 <class 'str'>
X298 <class 'str'>
X299 <class 'str'>
X300 <class 'str'>
X301 <class 'str'>
X302 <class 'str'>
X304 <class 'str'>
X305 <class 'str'>
X306 <class 'str'>
X307 <class 'str'>
X308 <class 'str'>
X309 <class 'str'>
X310 <class 'str'>
X311 <class 'str'>
X312 <class 'str'>
X313 <class 'str'>
X314 <class 'str'>
X315 <class 'str'>
X316 <class 'str'>
X317 <class 'str'>
X318 <class 'str'>
X319 <class 'str'>
X320 <class 'str'>
X321 <class 'str'>
X322 <class 'str'>
X323 <class 'str'>
X324 <class 'str'>
X325 <class 'str'>
X326 <class 'str'>
X327 <class 'str'>
X328 <class 'str'>
X329 <class 'str'>
X330 <class 'str'>
X331 <class 'str'>
X332 <class 'str'>
X333 <class 'str'>
X334 <class 'str'>
X335 <class 'str'>
X336 <class 'str'>
X337 <class 'str'>
X338 <class 'str'>
X339 <class 'str'>
X340 <class 'str'>
X341 <class 'str'>
X342 <class 'str'>
X343 <class 'str'>
X344 <class 'str'>
X345 <class 'str'>
X346 <class 'str'>
X347 <class 'str'>
X348 <class 'str'>
X349 <class 'str'>
X350 <class 'str'>
X351 <class 'str'>
X352 <class 'str'>
X353 <class 'str'>
X354 <class 'str'>
X355 <class 'str'>
X356 <class 'str'>
X357 <class 'str'>
X358 <class 'str'>
X359 <class 'str'>
X360 <class 'str'>
X361 <class 'str'>
X362 <class 'str'>
X363 <class 'str'>
X364 <class 'str'>
X365 <class 'str'>
X366 <class 'str'>
X367 <class 'str'>
X368 <class 'str'>
X369 <class 'str'>
X370 <class 'str'>
X371 <class 'str'>
X372 <class 'str'>
X373 <class 'str'>
X374 <class 'str'>
X375 <class 'str'>
X376 <class 'str'>
X377 <class 'str'>
X378 <class 'str'>
X379 <class 'str'>
X380 <class 'str'>
X382 <class 'str'>
X383 <class 'str'>
X384 <class 'str'>
X385 <class 'str'>

In [18]:
for i in data.columns:
    print(i,len(data[i].unique()))

ID 4209
y 2545
X0 47
X1 27
X2 44
X3 7
X4 4
X5 29
X6 12
X8 25
X10 2
X11 1
X12 2
X13 2
X14 2
X15 2
X16 2
X17 2
X18 2
X19 2
X20 2
X21 2
X22 2
X23 2
X24 2
X26 2
X27 2
X28 2
X29 2
X30 2
X31 2
X32 2
X33 2
X34 2
X35 2
X36 2
X37 2
X38 2
X39 2
X40 2
X41 2
X42 2
X43 2
X44 2
X45 2
X46 2
X47 2
X48 2
X49 2
X50 2
X51 2
X52 2
X53 2
X54 2
X55 2
X56 2
X57 2
X58 2
X59 2
X60 2
X61 2
X62 2
X63 2
X64 2
X65 2
X66 2
X67 2
X68 2
X69 2
X70 2
X71 2
X73 2
X74 2
X75 2
X76 2
X77 2
X78 2
X79 2
X80 2
X81 2
X82 2
X83 2
X84 2
X85 2
X86 2
X87 2
X88 2
X89 2
X90 2
X91 2
X92 2
X93 1
X94 2
X95 2
X96 2
X97 2
X98 2
X99 2
X100 2
X101 2
X102 2
X103 2
X104 2
X105 2
X106 2
X107 1
X108 2
X109 2
X110 2
X111 2
X112 2
X113 2
X114 2
X115 2
X116 2
X117 2
X118 2
X119 2
X120 2
X122 2
X123 2
X124 2
X125 2
X126 2
X127 2
X128 2
X129 2
X130 2
X131 2
X132 2
X133 2
X134 2
X135 2
X136 2
X137 2
X138 2
X139 2
X140 2
X141 2
X142 2
X143 2
X144 2
X145 2
X146 2
X147 2
X148 2
X150 2
X151 2
X152 2
X153 2
X154 2
X155 2
X156 2
X157 2
X158 2
X159 2
X160 2
X161 2
X162 2
X163 2
X164 2
X165 2
X166 2
X167 2
X168 2
X169 2
X170 2
X171 2
X172 2
X173 2
X174 2
X175 2
X176 2
X177 2
X178 2
X179 2
X180 2
X181 2
X182 2
X183 2
X184 2
X185 2
X186 2
X187 2
X189 2
X190 2
X191 2
X192 2
X194 2
X195 2
X196 2
X197 2
X198 2
X199 2
X200 2
X201 2
X202 2
X203 2
X204 2
X205 2
X206 2
X207 2
X208 2
X209 2
X210 2
X211 2
X212 2
X213 2
X214 2
X215 2
X216 2
X217 2
X218 2
X219 2
X220 2
X221 2
X222 2
X223 2
X224 2
X225 2
X226 2
X227 2
X228 2
X229 2
X230 2
X231 2
X232 2
X233 1
X234 2
X235 1
X236 2
X237 2
X238 2
X239 2
X240 2
X241 2
X242 2
X243 2
X244 2
X245 2
X246 2
X247 2
X248 2
X249 2
X250 2
X251 2
X252 2
X253 2
X254 2
X255 2
X256 2
X257 2
X258 2
X259 2
X260 2
X261 2
X262 2
X263 2
X264 2
X265 2
X266 2
X267 2
X268 1
X269 2
X270 2
X271 2
X272 2
X273 2
X274 2
X275 2
X276 2
X277 2
X278 2
X279 2
X280 2
X281 2
X282 2
X283 2
X284 2
X285 2
X286 2
X287 2
X288 2
X289 1
X290 1
X291 2
X292 2
X293 1
X294 2
X295 2
X296 2
X297 1
X298 2
X299 2
X300 2
X301 2
X302 2
X304 2
X305 2
X306 2
X307 2
X308 2
X309 2
X310 2
X311 2
X312 2
X313 2
X314 2
X315 2
X316 2
X317 2
X318 2
X319 2
X320 2
X321 2
X322 2
X323 2
X324 2
X325 2
X326 2
X327 2
X328 2
X329 2
X330 1
X331 2
X332 2
X333 2
X334 2
X335 2
X336 2
X337 2
X338 2
X339 2
X340 2
X341 2
X342 2
X343 2
X344 2
X345 2
X346 2
X347 1
X348 2
X349 2
X350 2
X351 2
X352 2
X353 2
X354 2
X355 2
X356 2
X357 2
X358 2
X359 2
X360 2
X361 2
X362 2
X363 2
X364 2
X365 2
X366 2
X367 2
X368 2
X369 2
X370 2
X371 2
X372 2
X373 2
X374 2
X375 2
X376 2
X377 2
X378 2
X379 2
X380 2
X382 2
X383 2
X384 2
X385 2

In [19]:
# if you do one hot encoding here it will give a lot of new featuers so it can be a curese of dimensionality

In [21]:
pd.get_dummies(data, drop_first = True).shape

(4209, 557)

In [22]:
data.shape # see we have more features, so it not possible to train a model like this, so we have alternate

(4209, 378)

* We're going to take first 10 to 20 most frequent features and we do the encoding remaining all the features are 0, tooked features are 1.

In [26]:
data.X2.value_counts().head(20)
# This for first features, we select the first 10 and do the label encoding and remaining all are zero.

as    1659
ae     496
ai     415
m      367
ak     265
r      153
n      137
s       94
f       87
e       81
aq      63
ay      54
a       47
t       29
k       25
i       25
b       21
ao      20
ag      19
z       19
Name: X2, dtype: int64

In [29]:
# let's take the top 10 values to do the encoding

top_10 = [i for i in data.X2.value_counts().sort_values(ascending = True).head(10).index]

In [30]:
top_10 # top 10 features this values are all 1 and remaining all are zero.

['ar', 'am', 'j', 'af', 'o', 'aa', 'c', 'l', 'au', 'av']

In [31]:
for i in top_10:
    data[i] = np.where(data['X2'] == i, 1, 0)

In [33]:
data[['X2'] + top_10].head()

   X2  ar  am  j  af  o  aa  c  l  au  av
0  at   0   0  0   0  0   0  0  0   0   0
1  av   0   0  0   0  0   0  0  0   0   1
2   n   0   0  0   0  0   0  0  0   0   0
3   n   0   0  0   0  0   0  0  0   0   0
4   n   0   0  0   0  0   0  0  0   0   0

In [34]:
# I am going to take smaller dataset
data = data.iloc[:,2:7]

In [35]:
data.head()

   X0 X1  X2 X3 X4
0   k  v  at  a  d
1   k  t  av  e  d
2  az  w   n  c  d
3  az  t   n  f  d
4  az  v   n  f  d

In [36]:
# I am going to do encoding fo all

In [37]:
def one_hot(data, variable, top):
    for i in top:
        data[variable +'_'+ i] = np.where(data[variable] == i, 1, 0)

In [39]:
one_hot(data, 'X2', top_10)

In [40]:
data.head() 
# for like that we can run a for loop for all the columns
# it will reduce the number of features comparing to the one hot encodings.

,X0,X1,X2,X3,X4,X2_ar,X2_am,X2_j,X2_af,X2_o,X2_aa,X2_c,X2_l,X2_au,X2_av
0,k,v,at,a,d,0,0,0,0,0,0,0,0,0,0
1,k,t,av,e,d,0,0,0,0,0,0,0,0,0,1
2,az,w,n,c,d,0,0,0,0,0,0,0,0,0,0
3,az,t,n,f,d,0,0,0,0,0,0,0,0,0,0
4,az,v,n,f,d,0,0,0,0,0,0,0,0,0,0